### ISSUE TITLE
Crashes stemming from [CleverTap profilePush:] in SDK v3.9.2

### ISSUE THREAD

**Issue by AlexGingell** [CleverTap/clevertap-ios-sdk#108] opened 2021-03-08 12:35 UTC
We have some rare production crash reports showing two different types of crash resulting from this call. We offer links to the crash reports and hope this may be of service.

SIGSEGV(SEGV_MAPERR) observed:
https://insta.co/crashes/GZ0Siv-7Ba4LcKxPM_742A

SIGTRAP(TRAP_BRKPT) observed:
https://insta.co/crashes/jGZC1TBRdlZ-5rsLVjbHCw

**Comment by Aditi3** [comment] 2021-03-16 04:20
hi @AlexGingell, I tried to repro the crash while pushing/ updating the user profile but failed. Also, looking at the frequency of the crash I'm sure the scenario will not be easily reproducible. 

Nonetheless, I am working on it to understand the cases where it could happen. In case I am able to reproduce the same, I would surely get it fixed in the upcoming SDK release.

**Closed** 2021-05-16 01:05 UTC

**Comment by Aditi3** [comment] 2021-05-16 01:15
I am going to close this. We don't have a good way to debug this crash without repro steps and looks like this is hardly happening by looking at the frequency.
