### ISSUE TITLE
Crashes stemming from [CTLocalDataStore _persistLocalProfileAsync]_block_invoke (CTLocalDataStore.m:638) in SDK v3.9.2

### ISSUE THREAD

**Issue by AlexGingell** [CleverTap/clevertap-ios-sdk#109] opened 2021-03-08 12:37 UTC
Here is a link to a detailed crash report:
https://insta.co/crashes/ZtIYxSKSP3tKYmVLdQmZtw

**Comment by Aditi3** [comment] 2021-03-15 16:05
more details and duplicate of #108

**Closed** 2021-03-16 04:20 UTC
