### ISSUE TITLE
'CleverTap+ABTesting.h' file not found

### ISSUE THREAD

**Issue by rabindrachhachan** [CleverTap/clevertap-ios-sdk#125] opened 2021-04-30 00:40 UTC
"react-native":0.64.0
"clevertap-react-native": "0.5.0",

On Opening Xcode, during the indexing it is failing  saying 'CleverTap+ABTesting.h' file not found

pod file

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

project 'x_app',

target 'XProd' do

  config = use_native_modules!

  use_react_native!(
    :path => config["reactNativePath"],
    :hermes_enabled => false
  )
  pod "CleverTap-iOS-SDK"

  target 'X_appTests' do
    inherit! :complete

  end

  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end
end

**Comment by Aditi3** [comment] 2021-04-30 05:04
Closing this because it's a duplicate of https://github.com/CleverTap/clevertap-react-native/issues/147. Please check recommended workaround [here](https://github.com/CleverTap/clevertap-react-native/issues/147#issuecomment-820489064).

**Closed by Aditi3** 2021-04-30 05:04 UTC
