### ISSUE TITLE
Lot's of crash at CTLocalDataStore persistEvent:] (collected from firebase)

### ISSUE THREAD

**Issue by xueminlee** [CleverTap/clevertap-ios-sdk#160] opened 2022-01-19 11:00 UTC
We find the crash from firebase, please see below log.

Crashed: com.clevertap.profileBackgroundQueue:46W-48Z-R85Z
0  libobjc.A.dylib                0x2878 objc_retain + 8
1  CoreFoundation                 0x1ee04 __NSDictionaryM_new + 616
2  CoreFoundation                 0x326c0 _NSDictionaryI_mutableCopyWithZone + 200
3  CleverTapSDK                   0x53fd0 __33-[CTLocalDataStore persistEvent:]_block_invoke + 181 (CTLocalDataStore.m:181)
4  libdispatch.dylib              0x631a4 _dispatch_call_block_and_release + 24
5  libdispatch.dylib              0x641a8 _dispatch_client_callout + 16
6  libdispatch.dylib              0xa0e4 _dispatch_lane_serial_drain$VARIANT$mp + 644
7  libdispatch.dylib              0xab94 _dispatch_lane_invoke$VARIANT$mp + 408
8  libdispatch.dylib              0x14760 _dispatch_workloop_worker_thread + 632
9  libsystem_pthread.dylib        0x4e84 _pthread_wqthread + 284
10 libsystem_pthread.dylib        0x49f0 start_wqthread + 8

**Comment by akashvercetti** [comment] 2022-01-19 13:38
Hi @xueminlee 

We tried reproducing the issue at our end but found no success. Could you please provide with us the following details so that we can investigate further?

Are you able to reproduce this yourself? If yes, do let us know the steps to reproduce the same.
Do you only see it via user crash reports?
The SDK Version
iOS Version

**Comment by g212gs** [comment] 2022-01-25 10:40
I also found the crash in my app for the CleverTap-iOS-SDK (3.10.0):

Crash detail:
### CTLocalDataStore.m line 619
### -[CTLocalDataStore persistLocalProfileIfRequired]



**Crashed: com.clevertap.serialQueue:**
**EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000f4ed1ec40**


`Crashed: com.clevertap.serialQueue:ID`
`0  libobjc.A.dylib                0x2bf0 objc_release + 16`
`1  AppName                          0xca9bdc -[CTLocalDataStore persistLocalProfileIfRequired] + 619 (CTLocalDataStore.m:619)`
`2  AppName                          0xca949c -[CTLocalDataStore setProfileFields:fromUpstream:] + 540 (CTLocalDataStore.m:540)`
`3  AppName                          0xcc6de0 __25-[CleverTap profilePush:]_block_invoke_2 + 3432 (CleverTap.m:3432)`
`4  AppName                          0xcaceb4 +[CTProfileBuilder build:completionHandler:] + 89 (CTProfileBuilder.m:89)`
`5  AppName                          0xcc6c68 __25-[CleverTap profilePush:]_block_invoke + 3469 (CleverTap.m:3469)`
`6  libdispatch.dylib              0x2914 _dispatch_call_block_and_release + 32`
`7  libdispatch.dylib              0x4660 _dispatch_client_callout + 20`
`8  libdispatch.dylib              0xbde4 _dispatch_lane_serial_drain + 672`
`9  libdispatch.dylib              0xc958 _dispatch_lane_invoke + 392`
`10 libdispatch.dylib              0x171a8 _dispatch_workloop_worker_thread + 656`
`11 libsystem_pthread.dylib        0x10f4 _pthread_wqthread + 288`
`12 libsystem_pthread.dylib        0xe94 start_wqthread + 8`

**Comment by akashvercetti** [comment] 2022-01-27 06:14
@g212gs the stack trace points to `profilePush` . Could you please provide the reproduction steps to make it easier for us to trace this?

**Comment by peppermints** [comment] 2022-03-04 02:51
> I also found the crash in my app for the CleverTap-iOS-SDK (3.10.0):
> 
> Crash detail:
> 
> ### CTLocalDataStore.m line 619
> ### -[CTLocalDataStore persistLocalProfileIfRequired]
> **Crashed: com.clevertap.serialQueue:** **EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000f4ed1ec40**
> 
> `Crashed: com.clevertap.serialQueue:ID` `0 libobjc.A.dylib 0x2bf0 objc_release + 16` `1 AppName 0xca9bdc -[CTLocalDataStore persistLocalProfileIfRequired] + 619 (CTLocalDataStore.m:619)` `2 AppName 0xca949c -[CTLocalDataStore setProfileFields:fromUpstream:] + 540 (CTLocalDataStore.m:540)` `3 AppName 0xcc6de0 __25-[CleverTap profilePush:]_block_invoke_2 + 3432 (CleverTap.m:3432)` `4 AppName 0xcaceb4 +[CTProfileBuilder build:completionHandler:] + 89 (CTProfileBuilder.m:89)` `5 AppName 0xcc6c68 __25-[CleverTap profilePush:]_block_invoke + 3469 (CleverTap.m:3469)` `6 libdispatch.dylib 0x2914 _dispatch_call_block_and_release + 32` `7 libdispatch.dylib 0x4660 _dispatch_client_callout + 20` `8 libdispatch.dylib 0xbde4 _dispatch_lane_serial_drain + 672` `9 libdispatch.dylib 0xc958 _dispatch_lane_invoke + 392` `10 libdispatch.dylib 0x171a8 _dispatch_workloop_worker_thread + 656` `11 libsystem_pthread.dylib 0x10f4 _pthread_wqthread + 288` `12 libsystem_pthread.dylib 0xe94 start_wqthread + 8`

same issue

**Comment by g212gs** [comment] 2022-03-04 04:59
> @g212gs the stack trace points to `profilePush` . Could you please provide the reproduction steps to make it easier for us to trace this?

-> majorly I found this from firebase crashlytics, and couldn't reproduce this manually, but yes... from the trace points, we can say, it's from `profilePush` only.

**Comment by kaungsoe** [comment] 2022-05-09 07:48
I'm also having the same problem. @g212gs found any fix for it? Here is the log from firebase Crashlytics 

Crashed: com.clevertap.serialQueue:8WR-R6R-955Z
0  libobjc.A.dylib                0x3970 objc_retain + 16
1  CleverTapSDK                   0x555fc -[CTLocalDataStore persistLocalProfileIfRequired] + 614 (CTLocalDataStore.m:614)
2  CleverTapSDK                   0x54eec -[CTLocalDataStore setProfileFields:fromUpstream:] + 540 (CTLocalDataStore.m:540)
3  CleverTapSDK                   0x19854 __25-[CleverTap profilePush:]_block_invoke_2 + 3332 (CleverTap.m:3332)
4  CleverTapSDK                   0x5a7c4 +[CTProfileBuilder build:completionHandler:] + 87 (CTProfileBuilder.m:87)
5  CleverTapSDK                   0x196dc __25-[CleverTap profilePush:]_block_invoke + 3369 (CleverTap.m:3369)
6  libdispatch.dylib              0x1e68 _dispatch_call_block_and_release + 32
7  libdispatch.dylib              0x3a2c _dispatch_client_callout + 20
8  libdispatch.dylib              0xb124 _dispatch_lane_serial_drain + 668
9  libdispatch.dylib              0xbc80 _dispatch_lane_invoke + 392
10 libdispatch.dylib              0x16500 _dispatch_workloop_worker_thread + 648
11 libsystem_pthread.dylib        0x10bc _pthread_wqthread + 288
12 libsystem_pthread.dylib        0xe5c start_wqthread + 8

**Comment by akashvercetti** [comment] 2022-05-17 04:52
Hi, Could you try updating to the latest version 4.0.1 and checking if it helps?

**Comment by nishant-clevertap** [comment] 2022-10-11 07:16
Hi,
This has been fixed in latest release(v4.1.3).
https://github.com/CleverTap/clevertap-ios-sdk/releases/tag/4.1.3

**Closed by nishant-clevertap** 2022-10-11 07:16 UTC
