### ISSUE TITLE
Crash App for Receive In-App Notification With Orientation's App Is Landscape And Layout is Potrait

### ISSUE THREAD

**Issue by alcalyx** [CleverTap/clevertap-ios-sdk#39] opened 2020-01-16 09:17 UTC
You can take a look this picture about error crash
![Screen Shot 2020-01-16 at 15 27 47](https://user-images.githubusercontent.com/48911103/72510079-5b2c8a80-387b-11ea-87dd-7c5d435b9d20.png)
My app has landscape orientation and when my app received In-App Notification with potrait layout. My app encountered crash for iOS 9 - 12. I used version for iOS SDK Clevertap with the version is 3.6.0 How i can avoid the crash for that case ?
Thank you

**Comment by Aditi3** [comment] 2020-01-16 10:10
Hi @alcalyx 

We too have noticed the problem and released the SDK with required changes to respect device orientation.

SDK version 3.7.0 and above comes with the fix. Therefore, I request you to update to 3.7.0 and verify the same.

Do let us know it goes for you.

**Comment by alcalyx** [comment] 2020-01-17 04:14
Could you reopen this issue? because i have updated the version into 3.7.2 but i still encountered the crash.

**Comment by Aditi3** [comment] 2020-01-17 04:56
Hi @alcalyx 

I quickly tested the scenario you described and seems to be working correctly. 

To understand better and debug further I request you to send the crash stack trace and the campaign link to us on support@clevertap.com?

Surely, we will look into it.

**Comment by alcalyx** [comment] 2020-01-17 06:26
Sure? have you set the app just support landscape for all view controllers? and you create In-App Notification with type content is Cover and the layout is just potrait. I found the crash when received the in app notification

**Comment by Aditi3** [comment] 2020-01-17 09:25
Hey, @alcalyx I have enabled Landscape device orientation in the Test Application and created Cover in-app and selected portrait mode. 

It seems to be working correctly for the iPhones running on iOS 13.x and below and iPad running on iOS 13.x. I manage to reproduce the problem on iPad running on iOS 12.x. 

Thank you so much for bringing this up and sorry for the inconvenience caused to you. 

The release with the fix will be available soon. We will keep you posted.

For now, I request you Select a Landscape layout for your In-Apps in the CleverTap Dashboard. The configuration handles the crash.

**Comment by alcalyx** [comment] 2020-01-17 09:58
I'm happy to help you about raise up this issue. Keep give me update in this github issue or you can send an email directly to me to give me update: satrio@mokapos.com
Thank you so much @Aditi3

**Comment by alcalyx** [comment] 2020-01-22 06:22
Hi @Aditi3 , i just want to know about the estimation of update regarding this issue, when we can update and free from this crash? And just want to confirm. What kind of iOS that will be covered for this issue? are covered for iOS 9 - 12 ?
Thank you

**Comment by Aditi3** [comment] 2020-01-23 09:43
Hi @alcalyx 

As above mentioned in my last comment, for now, I request you Select a Landscape layout for your In-Apps in the CleverTap Dashboard. The configuration handles the crash. 

We experience the problem on the iPad running on iOS 8.x - 12.x and will be adding the fix for the same. 

We have taken this up in our roadmap and working on a fix for this. It will be included in our next release. You can expect the release by end of February as the fix comes with a new feature.

Thank you.

**Comment by evanemelgamoka** [comment] 2020-02-28 03:49
Is there any update on this @Aditi3 ?

**Comment by Aditi3** [comment] 2020-02-28 04:46
Hi @evanemelgamoka 

We have already added a fix in our development branch. 

You can expect the release early next week. Apologies for the delay. 

Thanks!

**Comment by evanemelgamoka** [comment] 2020-02-28 04:53
Nice, thanks for the good news @Aditi3 👍

**Comment by evanemelgamoka** [comment] 2020-03-11 04:35
Hi @Aditi3  is there any upate on the new release?

**Comment by Aditi3** [comment] 2020-03-11 10:50
Hi @evanemelgamoka 

Here is the link of the latest release that comes with the fix
https://github.com/CleverTap/clevertap-ios-sdk/releases/tag/3.7.3

Thanks for your patience.

**Comment by evanemelgamoka** [comment] 2020-03-11 11:03
Fantastic news, thank you @Aditi3 💯

**Closed** 2020-04-07 23:36 UTC
